version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: winergy-postgres
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: winergy-api
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  docker-nest-postgres:
